hmrc/income-tax-employment

conf/application.conf

SASS-000 - Enabled hmrc BackendFilters in play.http.filters

---

app/connectors/GetEmploymentListConnector.scala
app/connectors/httpParsers/GetEmploymentListHttpParser.scala
app/controllers/GetEmploymentListController.scala
app/models/GetEmploymentListModel.scala
app/services/GetEmploymentListService.scala
app/utils/DESTaxYearHelper.scala
it/connectors/GetEmploymentListConnectorSpec.scala
test/controllers/GetEmploymentListControllerSpec.scala
test/models/DesErrorBodyModelSpec.scala
test/models/GetEmploymentListModelSpec.scala
test/services/GetEmploymentListServiceSpec.scala
test/utils/DESTaxYearHelperSpec.scala
test/utils/TestUtils.scala

Added functionality to call the GetEmploymentList api in des
https://jira.tools.tax.service.gov.uk/browse/SASS-542

SASS-663: Added getEmploymentList des api

---

app/connectors/GetEmploymentDataConnector.scala
app/connectors/httpParsers/GetEmploymentDataHttpParser.scala
app/controllers/GetEmploymentDataController.scala
app/models/DesErrorBody.scala
app/models/GetEmploymentDataModel.scala
app/services/GetEmploymentDataService.scala
app/utils/ViewParameterValidation.scala
it/connectors/GetEmploymentDataConnectorSpec.scala
test/controllers/GetEmploymentDataControllerSpec.scala
test/models/GetEmploymentDataModelSpec.scala
test/services/GetEmploymentDataServiceSpec.scala
test/utils/TestUtils.scala
test/utils/ViewParameterValidationSpec.scala

Adding des connector for get employment data and unit/integration tests
https://jira.tools.tax.service.gov.uk/browse/SASS-543

SASS-543: Added des connector for get employment data

---

app/connectors/DesConnector.scala
app/controllers/GetEmploymentsController.scala
app/controllers/predicates/AuthorisedAction.scala
app/services/EmploymentOrchestrationService.scala
project/AppDependencies.scala
test/connectors/DesConnectorSpec.scala
test/controllers/GetEmploymentsControllerSpec.scala
test/services/EmploymentOrchestrationServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-602

downgraded bootstrap to keep headers

---

app/models/shared/Pay.scala
it/connectors/GetEmploymentDataConnectorSpec.scala
test/models/DESEmploymentDataSpec.scala
test/utils/TestUtils.scala

update Pay model and tests
[SASS-873](https://jira.tools.tax.service.gov.uk/browse/SASS-864)

update payModel and relevant tests

---

app/connectors/httpParsers/GetEmploymentListHttpParser.scala
app/models/DES/DESEmploymentList.scala
app/services/EmploymentOrchestrationService.scala
it/connectors/GetEmploymentListConnectorSpec.scala
test/services/EmploymentOrchestrationServiceSpec.scala
test/utils/TestUtils.scala

Changed model to reflect what des returns

updated model and added tests

---

app/connectors/CreateEmploymentConnector.scala
app/connectors/httpParsers/CreateEmploymentHttpParser.scala
app/controllers/CreateEmploymentController.scala
app/models/shared/AddEmploymentRequestModel.scala
app/models/shared/AddEmploymentResponseModel.scala
app/services/CreateEmploymentService.scala
it/connectors/CreateEmploymentConnectorSpec.scala
it/connectors/GetEmploymentBenefitsConnectorSpec.scala
test/controllers/CreateEmploymentControllerSpec.scala
test/services/CreateEmploymentServiceSpec.scala

[SASS-914] https://jira.tools.tax.service.gov.uk/browse/SASS-914

SASS-914 - Added createOrAmendEmployment connector

---

app/connectors/PutEmploymentFinancialDataConnector.scala
app/connectors/httpParsers/PutEmploymentFinancialDataHttpParser.scala
app/controllers/PutEmploymentFinancialDataController.scala
app/models/DES/DESEmploymentFinancialData.scala
app/services/PutEmploymentFinancialDataService.scala
conf/app.routes
it/connectors/PutEmploymentFinancialDataConnectorSpec.scala
it/helpers/WiremockStubHelpers.scala
test/controllers/PutEmploymentFinancialDataControllerSpec.scala
test/models/DESEmploymentFinancialDataSpec.scala
test/services/PUTEmploymentFinancialDataServiceSpec.scala
test/utils/TestUtils.scala

Adding connector/controller etc for the createUpdate financial data des api
https://docs.google.com/document/d/1vovuKZA3VE1_uRK6CFMXhDPVhzbwapQz/edit#
https://jira.tools.tax.service.gov.uk/browse/SASS-770

SASS-770: Adding new createUpdate financial data des api

---

app/connectors/DeleteEmploymentConnector.scala
app/connectors/httpParsers/DeleteEmploymentHttpParser.scala
app/controllers/DeleteEmploymentController.scala
app/services/EmploymentService.scala
it/connectors/DeleteEmploymentConnectorSpec.scala
it/helpers/WiremockStubHelpers.scala
test/controllers/CreateEmploymentControllerSpec.scala
test/controllers/DeleteEmploymentControllerSpec.scala
test/services/EmploymentServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-918

SASS-918 - Added DeleteEmploymentConnector

---

project/AppDependencies.scala

updated dependancies
[SASS-920]

SASS-920b - updated dependancies

---

app/connectors/UpdateEmploymentConnector.scala
app/connectors/httpParsers/UpdateEmploymentDataHttpParser.scala
app/controllers/CreateEmploymentController.scala
app/controllers/UpdateEmploymentController.scala
app/models/shared/EmploymentRequestModel.scala
app/services/EmploymentService.scala
it/connectors/CreateEmploymentConnectorSpec.scala
it/connectors/UpdateEmploymentConnectorSpec.scala
it/helpers/WiremockStubHelpers.scala
test/controllers/CreateEmploymentControllerSpec.scala
test/controllers/UpdateEmploymentControllerSpec.scala
test/services/EmploymentServiceSpec.scala

Adding connector for the update employment api
https://jira.tools.tax.service.gov.uk/browse/SASS-771

Sass 771: Adding connector for the update employment api

---

app/connectors/IgnoreEmploymentConnector.scala
app/connectors/httpParsers/IgnoreEmploymentHttpParser.scala
app/services/EmploymentService.scala
it/connectors/IgnoreEmploymentConnectorSpec.scala
it/helpers/WiremockStubHelpers.scala
test/services/EmploymentServiceSpec.scala

[SASS-980](https://jira.tools.tax.service.gov.uk/browse/SASS-980)

[SASS-980] ignoreEmployments connector

---

app/config/AppConfig.scala
app/connectors/GetEmploymentDataConnector.scala
app/connectors/IFConnector.scala
conf/application.conf
it/connectors/GetEmploymentDataConnectorSpec.scala
it/helpers/WiremockSpec.scala
project/AppDependencies.scala
project/plugins.sbt

Migrate employment API #1647 Get employment data to speak to IF

---

app/services/EmploymentService.scala
app/utils/ViewParameterValidation.scala
test/services/EmploymentServiceSpec.scala

removed all parameter from delete employment orchestration
https://jira.tools.tax.service.gov.uk/browse/SASS-1107

removed all as a parameter to remove employment

---

app/models/shared/Pay.scala
project/AppDependencies.scala
test/controllers/GetEmploymentsControllerSpec.scala
test/models/AllEmploymentDataModelSpec.scala
test/models/DESEmploymentDataSpec.scala
test/utils/TestUtils.scala

Removing tips and other payments from the model
[SASS-1126](https://jira.tools.tax.service.gov.uk/browse/SASS-1126)

Removed tips from model

---

app/config/AppConfig.scala
app/connectors/GetEmploymentDataConnector.scala
app/connectors/GetEmploymentListConnector.scala
app/connectors/IFConnector.scala
conf/application.conf
it/connectors/GetEmploymentListConnectorSpec.scala
project/AppDependencies.scala
project/plugins.sbt

- Updating the employment list connector to use IF
- Splitting out the IF token to have seperate tokens for each API
- Updating the dependencies
https://jira.tools.tax.service.gov.uk/browse/SASS-1193

updated get employment list connector to use IF

---

app/connectors/IgnoreEmploymentConnector.scala
conf/application.conf
it/connectors/IgnoreEmploymentConnectorSpec.scala

Switched api 1664 connector to IF
[SASS-1195](https://jira.tools.tax.service.gov.uk/browse/SASS-1195)

made Ignore Employment Connector use IF

---

app/connectors/UpdateEmploymentConnector.scala
conf/application.conf
it/connectors/UpdateEmploymentConnectorSpec.scala

Changes to update employment API #1162 to use IF
- app-config-qa PR https://github.com/hmrc/app-config-qa/pull/13373
- app-config-production PR https://github.com/hmrc/app-config-production/pull/12966
[SASS-1196](https://jira.tools.tax.service.gov.uk/browse/SASS-1196)

Changes to update employment API #1662 to use IF

---

app/connectors/CreateUpdateEmploymentFinancialDataConnector.scala
app/models/CreateUpdateEmploymentRequest.scala
app/models/DES/DESEmploymentFinancialData.scala
conf/application.conf
it/connectors/CreateUpdateEmploymentFinancialDataConnectorSpec.scala
test/models/DESEmploymentFinancialDataSpec.scala
test/utils/TestUtils.scala

- Changed CreateUpdateEmploymentFinancialDataConnector to point to IF
- Aligned API to the latest spec (removed lumpSums object)
[SASS-1198](https://jira.tools.tax.service.gov.uk/browse/SASS-1198)
- PR for updating the stub: https://github.com/hmrc/income-tax-submission-stub/pull/70
- PR for adding token in QA: https://github.com/hmrc/app-config-qa/pull/13468
- PR for adding token in Prod: https://github.com/hmrc/app-config-production/pull/13098

SASS-1198 - Migrate create/update employment financial data API 1643 to IF

---

app/services/EmploymentService.scala
test/services/EmploymentServiceSpec.scala

Changes SERVICE_UNAVAILABLE error to INTERNAL_SERVER_ERROR to avoid unnecessary re-trys.
[SASS-1907](https://jira.tools.tax.service.gov.uk/browse/SASS-1907)

SASS-1907 - Retry mechanism on employment API error.

---

app/connectors/CreateEmploymentConnector.scala
app/connectors/CreateUpdateEmploymentFinancialDataConnector.scala
app/connectors/GetEmploymentDataConnector.scala
app/connectors/GetEmploymentListConnector.scala
app/connectors/IFConnector.scala
app/connectors/IgnoreEmploymentConnector.scala
app/connectors/UnignoreEmploymentConnector.scala
app/connectors/UpdateEmploymentConnector.scala
app/connectors/httpParsers/UnignoreEmploymentHttpParser.scala
app/controllers/UnignoreEmploymentController.scala
app/services/EmploymentService.scala
conf/app.routes
conf/application.conf
it/connectors/UnignoreEmploymentConnectorSpec.scala
test/controllers/UnignoreEmploymentControllerSpec.scala
test/services/EmploymentServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2493

SASS-2556 Added unignore API

---

conf/app.routes
project/AppDependencies.scala

correct route

---

app/connectors/DeleteEmploymentConnector.scala
app/connectors/IFConnector.scala
app/connectors/httpParsers/DeleteEmploymentHttpParser.scala
conf/application.conf
it/connectors/DeleteEmploymentConnectorSpec.scala
project/AppDependencies.scala

Update our endpoint for API 1663 Delete Employment
[SASS-2636](https://jira.tools.tax.service.gov.uk/browse/SASS-2597)

SASS-2636 Update API 1663 with latest spec

---

README.md
project/AppDependencies.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-2828

Updated readme

---

app/models/DES/DESEmploymentList.scala
app/models/frontend/AllEmploymentData.scala
test/controllers/GetEmploymentsControllerSpec.scala
test/models/AllEmploymentDataModelSpec.scala
test/models/DESEmploymentListSpec.scala
test/utils/TestUtils.scala

Align to latest spec for API #1645
[SASS-2763](https://jira.tools.tax.service.gov.uk/browse/SASS-2763)

Align to latest spec for API #1645

---

project/AppDependencies.scala

[SASS-3000](https://jira.tools.tax.service.gov.uk/browse/SASS-3000)

SASS-3000 - Updates library to prepare for relese.

---

app/controllers/predicates/AuthorisedAction.scala
conf/application.conf
test/controllers/predicates/AuthorisedActionSpec.scala
test/utils/TestUtils.scala

Increasing the minimum Confidence Level value to 250 rather than 200
https://jira.tools.tax.service.gov.uk/browse/SASS-3946
SASS-3946. Increase the 'Confidence Level' to 250 from 200

SASS-3946 Increase the 'Confidence Level' to 250 from 200

---

project/AppDependencies.scala

Update library versions

---

conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

Libraries upgrade

---

app/models/api/AwardedOrReceivedShare.scala
app/models/api/BenefitFromEmployerFinancedRetirementScheme.scala
app/models/api/Disability.scala
app/models/api/ForeignService.scala
app/models/api/LumpSum.scala
app/models/api/OtherEmploymentIncome.scala
app/models/api/RedundancyCompensationPaymentsOverExemption.scala
app/models/api/RedundancyCompensationPaymentsUnderExemption.scala
app/models/api/ShareAwardedShareSchemePlanType.scala
app/models/api/ShareOption.scala
app/models/api/ShareOptionSchemePlanType.scala
app/models/api/TaxableLumpSumsAndCertainIncome.scala
app/utils/JsonUtils.scala
test/models/api/OtherEmploymentIncomeSpec.scala
test/support/builders/api/BenefitFromEmployerFinancedRetirementSchemeBuilder.scala
test/support/builders/api/DisabilityBuilder.scala
test/support/builders/api/ForeignServiceBuilder.scala
test/support/builders/api/LumpSumBuilder.scala
test/support/builders/api/OtherEmploymentIncomeBuilder.scala
test/support/builders/api/RedundancyCompensationPaymentsOverExemptionBuilder.scala
test/support/builders/api/RedundancyCompensationPaymentsUnderExemptionBuilder.scala
test/support/builders/api/ShareAwardedOrReceivedBuilder.scala
test/support/builders/api/ShareOptionBuilder.scala
test/support/builders/api/TaxableLumpSumsAndCertainIncomeBuilder.scala

[SASS-4585](https://jira.tools.tax.service.gov.uk/browse/SASS-4585)

SASS-4585 - Employment lump sums backend model.

---

app/connectors/GetEmploymentDataConnector.scala
app/connectors/IFConnector.scala
it/connectors/GetEmploymentDataConnectorSpec.scala
test/support/builders/api/RedundancyCompensationPaymentsOverExemptionBuilder.scala
test/support/utils/TaxYearUtils.scala

[SASS-5051](https://jira.tools.tax.service.gov.uk/browse/SASS-5051)

SASS-5051 Implement TYS APIs to handle future tax years

---

app/connectors/DeleteOtherEmploymentIncomeConnector.scala
app/connectors/parsers/DeleteOtherEmploymentsIncomeHttpParser.scala
it/connectors/DeleteOtherEmploymentIncomeConnectorSpec.scala
test/connectors/parsers/DeleteOtherEmploymentsIncomeHttpParserSpec.scala

[SASS-4737](https://jira.tools.tax.service.gov.uk/browse/SASS-4737)

SASS-4737 Implement 1619 Delete Other Employments Income

---

app/controllers/GetEmploymentsController.scala
app/models/frontend/AllEmploymentData.scala
app/services/EmploymentOrchestrationService.scala
test/controllers/GetEmploymentsControllerSpec.scala
test/models/AllEmploymentDataModelSpec.scala
test/services/EmploymentOrchestrationServiceSpec.scala
test/utils/TestUtils.scala

[SASS-5065](https://jira.tools.tax.service.gov.uk/browse/SASS-5065)

SASS-5065 Include the OtherEmploymentIncome as part of AllEmploymentData

---

app/config/AppConfig.scala
app/connectors/CreateUpdateEmploymentFinancialDataTYSConnector.scala
app/connectors/GetEmploymentDataConnector.scala
app/connectors/IFConnector.scala
app/connectors/parsers/CreateUpdateEmploymentFinancialDataTYSHttpParser.scala
app/models/CreateUpdateEmploymentRequest.scala
app/services/EmploymentService.scala
app/utils/PagerDutyHelper.scala
app/utils/TaxYearUtils.scala
conf/application.conf
it/connectors/CreateUpdateEmploymentFinancialDataTYSConnectorSpec.scala
project/plugins.sbt
test/connectors/parsers/CreateUpdateEmploymentFinancialDataTYSHttpParserSpec.scala
test/controllers/CreateUpdateEmploymentControllerSpec.scala
test/models/api/EmploymentFinancialDataSpec.scala
test/services/EmploymentServiceSpec.scala
test/utils/TaxYearUtilSpec.scala
test/utils/TestUtils.scala

[SASS-5555](https://jira.tools.tax.service.gov.uk/browse/SASS-5555)

SASS-5555 Create Update employment detail override API 1935

---

app/connectors/IFConnector.scala
app/connectors/OtherEmploymentIncomeIFConnector.scala
app/connectors/parsers/OtherEmploymentIncomeIFHttpParser.scala
app/services/OtherEmploymentIncomeService.scala
conf/application.conf
it/connectors/OtherEmploymentIncomeIFConnectorSpec.scala
test/connectors/parsers/OtherEmploymentIncomeIFHttpParserSpec.scala
test/services/OtherEmploymentIncomeServiceSpec.scala

SASS-7220: Add taxYear specific 1794 api

---

app/services/EmploymentOrchestrationService.scala
test/services/EmploymentOrchestrationServiceSpec.scala

SASS-7220: Fix tax year specific changes

---

app/connectors/IgnoreEmploymentConnector.scala
app/connectors/UnignoreEmploymentConnector.scala
build.sbt
conf/application.conf
conf/logback.xml
it/test/connectors/IgnoreEmploymentConnectorSpec.scala
it/test/connectors/UnignoreEmploymentConnectorSpec.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

SASS-8445: Add 1940 & 1800 TYS API

---

conf/app.routes

fix journey answers routes

---

app/common/EnrolmentCommon.scala
app/config/AppConfig.scala
app/controllers/predicates/AuthorisedAction.scala
app/models/User.scala
conf/application.conf
test/config/MockAppConfig.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/services/CommonTaskListServiceSpec.scala
test/support/UnitTest.scala
test/support/stubs/AppConfigStub.scala
test/utils/TestUtils.scala

- **SASS-10593: Add new config item to app config to toggle EMA + some test fixes**
- **SASS-10593: Add EMA logic and associated testing changes**

SASS-10593: Enable EMA

---

app/controllers/predicates/AuthorisedAction.scala
check.sh
project/plugins.sbt
test/controllers/predicates/AuthorisedActionSpec.scala

[SASS-10773] Handle non-Auth related exception in AuthAction and return ISE

---

project/AppDependencies.scala
project/plugins.sbt

Update dependencies
[MIPR-1948](https://jira.tools.tax.service.gov.uk/browse/MIPR-1948)

MIPR-1948: Upgrade Submissions dependencies
